version: '3'
services:
  homenginx:
    container_name: homenginx
    build: ./nginx
    volumes:
      - ./nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/var/www/index.html
      - ./assets/:/var/www/assets/
    ports:
      - 3005:8080
    command: [nginx, '-g', 'daemon off;']
