version: '3'
services:
  oncecardnginx:
    container_name: oncecardnginx
    build: ./nginx
    volumes:
      - ./nginx/conf.d/web.conf:/etc/nginx/conf.d/web.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/
      - ./assets/:/var/www/assets/
    ports:
      - 3005:8080
    command: [nginx, '-g', 'daemon off;']
